<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
    <Tailcalls>false</Tailcalls>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PhysicalConstantsTest.fs" />
    <Compile Include="MathTest.fs" />
    <Compile Include="ChemistryTest.fs" />
    <Compile Include="PhasesTest.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EoS.Core\EoS.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net462'">
    <PackageReference Update="System.ValueTuple" Version="4.6.1" />
  </ItemGroup>

</Project>
