<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <AssemblyName>eos</AssemblyName>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">net8.0;net8.0-windows;net462</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('Windows'))">net8.0;net462</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\EoS.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="('$(TargetFramework)'=='net8.0')">
    <RuntimeIdentifiers>linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition="('$(TargetFramework)'=='net8.0-windows')">
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition="('$(TargetFramework)'=='net8.0' Or '$(TargetFramework)'=='net8.0-windows') And ('$(PublishSelfContained)'=='true')">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
    <Tailcalls>false</Tailcalls>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="FormulaTool.fs" />
    <Compile Include="IndexTool.fs" />
    <Compile Include="PropertyTool.fs" />
    <Compile Include="OptimizationTool.fs" />
    <Compile Include="AdiabatTool.fs" />
    <Compile Include="FittingTool.fs" />
    <Compile Include="BitmapBox.fs" />
    <Compile Include="BitmapTool.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EoS.Core\EoS.Core.fsproj" />
    <ProjectReference Include="..\EoS.CommandLine\EoS.CommandLine.fsproj" />
    <ProjectReference Include="..\EoS.Optimization\EoS.Optimization.fsproj" />
    <ProjectReference Include="..\EoS.DebyeModel\EoS.DebyeModel.fsproj" />
    <ProjectReference Include="..\EoS.PolynomialModel\EoS.PolynomialModel.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)'=='net8.0') And ('$(RuntimeIdentifier)'=='linux-x64')">
    <PackageReference Include="Eto.Platform.Gtk" Version="2.10.1" />
  </ItemGroup>
  <ItemGroup Condition="('$(TargetFramework)'=='net8.0') And ('$(RuntimeIdentifier)'=='osx-x64' Or '$(RuntimeIdentifier)'=='osx-arm64')">
    <PackageReference Include="Eto.Platform.Mac64" Version="2.10.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net8.0-windows'">
    <PackageReference Include="Eto.Platform.Windows" Version="2.10.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net462'">
    <PackageReference Update="System.ValueTuple" Version="4.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <Product>EoS</Product>
    <Description>Command line interface to EoS functions</Description>
    <Copyright>Copyright ⓒ 2009-2025 Thomas Chust; Bayerisches Geoinstitut, Bayreuth; Ludwig-Maximilians-Universität, München</Copyright>
    <Version>2.1.0</Version>
    <Authors>Murphy</Authors>
    <PackageTags>f#;fsharp;eos;equation;state;mineral;physics;thermodynamics;simulation;gibbs;energy;minimization;optimization</PackageTags>
    <PackageProjectUrl>https://chust.org/repos/eos/</PackageProjectUrl>
    <PackageLicenseUrl>https://chust.org/repos/eos/doc/tip/LICENSE.txt</PackageLicenseUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>
